#ifndef ERRS_H
#define ERRS_H


namespace ex
{
    enum gameErrs
    {
        RENDERER_IS_ABSENT,
        CANNOT_ALLOCATE_MEM_GAMEFONTS,
        CANNOT_OPEN_FONT,
        CANNOT_ALLOCATE_MEM_STRINGTEXTURES,
        CANNOT_ALLOCATE_MEM_PICTURETEXTURES,
        CANNOT_CREATE_STRINGTEXTURE,
        CANNOT_CREATE_PICTURETEXTURE,
        LOADFROMTEXT_RENDERER_IS_ABSENT,
        LOADFROMTEXT_TEXTURE_IS_ABSENT,
        LOADFROMTEXT_NAME_IS_ABSENT,
        LOADFROMFILE_RENDERER_IS_ABSENT,
        LOADFROMFILE_TEXTURE_IS_ABSENT,
        LOADFROMFILE_UNABLE_LOAD_IMAGE,
        LOADFROMFILE_UNABLE_TO_CREATE_TEXTURE,
        LOADFROMFILE_NAME_IS_ABSENT,
        OK,
    };
}




#endif